{
    "delivery_order_id": null,
    "is_snoozed": false,
    "created_on": "2016-11-20T19:33:14+00:00",
    "updated_on": "2016-11-20T20:12:16+00:00",
    "source": "foodpanda",
    "discount_value": null,
    "discount_percentage": null,
    "delivery_boy_name": null,
    "delivery_boy_details": null,
    "customer": {
    "primary_number": 9540419750,
        "name": "harsha tanguturi ",
        "id": 1049032
},
    "address": {
    "created_on": "2016-11-20T19:33:13+00:00",
        "locality_id": null,
        "name": "Flat No. 801, C Block, Pilot Court Essel Towers, Near MG Road Gurgaon ",
        "sub_locality": null,
        "sub_locality_id": null,
        "locality": null,
        "customer_id": 1049032,
        "id": 157879,
        "address_type": "Home",
        "latitude": null,
        "city_id": null,
        "longitude": null,
        "city": null,
        "updated_on": null
},
    "delivery_by": "nomnom",
    "external_source_id": "s3ca-1l4p",
    "reset_alarm_level": 2,
    "alarm_levels": [3, 4, 5, 6, 7],
    "snooze_level": 0,
    "delivery_time": "2016-11-20T19:33:14+00:00",
    "reset_alarm_levels": [2],
    "promise_delivery_time": "2016-11-20T19:33:14+00:00",
    "delivery_boy_number": null,
    "delivery_instructions": null,
    "distance": 0,
    "sub_total": 475,
    "sub_order": {
    "coupon_discount": null,
        "created_on": "2016-11-20T19:33:14+00:00",
        "updated_on": null,
        "discount_percentage": null,
        "other_charges": 0,
        "delivery_charges": 29,
        "restaurant_id": 255,
        "coupon": "",
        "restaurant": {
        "external_pos_id": null,
            "latitude": "28.4926440000",
            "addresses": [{
            "created_on": "2016-10-09T17:35:56+00:00",
            "locality_id": 6250,
            "name": "",
            "sub_locality": {
                "latitude": "28.4942280000",
                "longitude": "77.0969400000",
                "name": "U Block",
                "id": 28782
            },
            "sub_locality_id": 28782,
            "locality": {
                "road_runnr_name": "DLF Phase 3, Phase 3, Gurgaon",
                "name": "DLF PHASE 3",
                "id": 6250
            },
            "customer_id": null,
            "id": 124412,
            "address_type": "Work",
            "latitude": null,
            "city_id": 3,
            "longitude": null,
            "city": {
                "name": "Gurgaon",
                "id": 3
            },
            "updated_on": "2016-10-09T17:38:28+00:00"
        }],
            "taxes": [{
            "rate": 13.13,
            "type": "vat_tax",
            "restaurant": 255,
            "id": 350
        }],
            "longitude": "77.0937880000",
            "name": "Zasty (DLF Phase 3, Gurgaon)",
            "branch_email": null,
            "branch_number": null,
            "pos_type": "nomnom",
            "id": 255
    },
    "packaging_charges": 0,
        "status": "created",
        "offer_percentage": null,
        "restaurant_sub_total": 475,
        "offer_value": null,
        "restaurant_total": 444,
        "items": [{
        "is_discountable": true,
        "dish_quantity_name": "Portion",
        "created_on": "2016-11-20T19:33:14+00:00",
        "dish_id": 24916,
        "dish_quantity": 1,
        "tax_category": [350],
        "dish_variation_name": "Chicken",
        "id": 449921,
        "dish_customization": [],
        "sub_order_id": 186543,
        "dish_name": "Pasta White Sauce",
        "pos_code": "Pasta White Sauce",
        "dish_quantity_id": 38139,
        "food_type": "non_veg",
        "dish_total": 185,
        "dish_pos_id": null,
        "dish_price": 185,
        "updated_on": null
    }, {
        "is_discountable": true,
        "dish_quantity_name": "Portion",
        "created_on": "2016-11-20T19:33:14+00:00",
        "dish_id": 24916,
        "dish_quantity": 1,
        "tax_category": [350],
        "dish_variation_name": "Veg",
        "id": 449922,
        "dish_customization": [],
        "sub_order_id": 186543,
        "dish_name": "Pasta White Sauce",
        "pos_code": "Pasta White Sauce",
        "dish_quantity_id": 38294,
        "food_type": "vegetarian",
        "dish_total": 165,
        "dish_pos_id": null,
        "dish_price": 165,
        "updated_on": null
    }, {
        "is_discountable": true,
        "dish_quantity_name": "Portion",
        "created_on": "2016-11-20T19:33:14+00:00",
        "dish_id": 24938,
        "dish_quantity": 1,
        "tax_category": [350],
        "dish_variation_name": "-",
        "id": 449923,
        "dish_customization": [],
        "sub_order_id": 186543,
        "dish_name": "Fried Rice",
        "pos_code": "Fried Rice",
        "dish_quantity_id": 38310,
        "food_type": "vegetarian",
        "dish_total": 125,
        "dish_pos_id": null,
        "dish_price": 125,
        "updated_on": null
    }],
        "taxes": [{
        "total": 0,
        "rate": 0,
        "type": "vat_tax"
    }, {
        "total": 0,
        "rate": 0,
        "type": "service_tax"
    }],
        "estimated_preparation_time": 0,
        "discount": null,
        "id": 186543,
        "estimated_delivery_time": 0,
        "order_id": 185438,
        "special_instructions": "",
        "restaurant_sub_total_discounted": null,
        "service_tax": null,
        "vat_tax": null,
        "coupon_percentage": null
},
    "alarm_level": 7,
    "customer_id": 1049032,
    "id": 185438,
    "order_status_log": [{
    "order_id": 185438,
    "status_log": 185438,
    "created_on": "2016-11-20T19:33:14+00:00",
    "owner": {
        "name": "foodpanda",
        "id": 348
    },
    "owner_type": "foodpanda",
    "status": "created",
    "owner_id": 348,
    "message": null,
    "id": 779824
}, {
    "order_id": 185438,
    "status_log": 185438,
    "created_on": "2016-11-20T19:57:27+00:00",
    "owner": {
        "name": "Zasty DLF phase 3",
        "id": 417
    },
    "owner_type": "restaurant",
    "status": "restaurant_confirmed",
    "owner_id": 417,
    "message": null,
    "id": 780082
}],
    "other_charges": null,
    "paid": true,
    "address_id": 157879,
    "external_id": null,
    "total_price": 444,
    "status": "confirmed"
}